// Realistic mock data for the care caller application
export const MOCK_PATIENTS = [
  {
    id: 'P001',
    name: 'Margaret Johnson',
    medication: 'Lisinopril 10mg',
    phone: '(555) 123-4567',
    status: 'pending',
  },
  {
    id: 'P002',
    name: 'Robert Chen',
    medication: 'Metformin 500mg',
    phone: '(555) 234-5678',
    status: 'completed',
  },
  {
    id: 'P003',
    name: 'Patricia Williams',
    medication: 'Albuterol Inhaler',
    phone: '(555) 345-6789',
    status: 'pending',
  },
  {
    id: 'P004',
    name: 'James Martinez',
    medication: 'Atorvastatin 20mg',
    phone: '(555) 456-7890',
    status: 'in_progress',
  },
  {
    id: 'P005',
    name: 'Linda Davis',
    medication: 'Ibuprofen 400mg',
    phone: '(555) 567-8901',
    status: 'completed',
  },
  {
    id: 'P006',
    name: 'Michael Anderson',
    medication: 'Amlodipine 5mg',
    phone: '(555) 678-9012',
    status: 'pending',
  },
  {
    id: 'P007',
    name: 'Barbara Taylor',
    medication: 'Simvastatin 40mg',
    phone: '(555) 789-0123',
    status: 'pending',
  },
  {
    id: 'P008',
    name: 'David Thomas',
    medication: 'Carbidopa/Levodopa',
    phone: '(555) 890-1234',
    status: 'completed',
  },
  {
    id: 'P009',
    name: 'Nancy Jackson',
    medication: 'Levothyroxine 75mcg',
    phone: '(555) 901-2345',
    status: 'pending',
  },
  {
    id: 'P010',
    name: 'Joseph White',
    medication: 'Albuterol + Tiotropium',
    phone: '(555) 012-3456',
    status: 'pending',
  },
];

export const MOCK_CALLS = [
  {
    id: 'C001',
    patient_name: 'Margaret Johnson',
    phone: '(555) 123-4567',
    medication: 'Lisinopril 10mg',
    dosage: '1 tablet daily',
    duration: '4m 32s',
    cost: 2.15,
    outcome: 'completed',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    needs_attention: false,
    ai_analysis: {
      quality_score: 92,
      sentiment: 'positive',
      summary: 'Patient confirmed medication adherence. No issues reported.',
      clinical_summary: 'Patient reports excellent medication compliance with Lisinopril 10mg daily. Blood pressure readings stable at 128/82. No adverse side effects noted. Patient states she is taking medication at the same time each morning with breakfast. Follow-up recommended in 3 months.',
      recommended_action: 'routine_refill',
      response_completeness: 92,
      conversation_flow: 93,
      data_accuracy: 91,
      guardrail_compliance: 95,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'very well',
      'What is your current weight in pounds?': '145',
      'What is your height in feet and inches?': '5 feet 6 inches',
      'How much weight have you lost this past month in pounds?': '2',
      'Any side effects from your medication this month?': 'no',
      'Are you satisfied with your rate of weight loss?': 'yes',
      'What is your goal weight in pounds?': '135',
      'Any requests about your dosage?': 'no',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'no',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'no',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Hello Margaret, this is the medication reminder call. how are you doing today?' },
      { role: 'patient', text: 'I\'m doing well, thank you for calling.' },
      { role: 'agent', text: 'That\'s wonderful to hear. I\'m calling to check in on your Lisinopril 10mg medication. Are you taking it as prescribed?' },
      { role: 'patient', text: 'Yes, I take one tablet every morning with my breakfast. I haven\'t missed a dose.' },
      { role: 'agent', text: 'That\'s excellent adherence. Have you experienced any side effects from the medication?' },
      { role: 'patient', text: 'No, I feel great. No dizziness or anything like that.' },
      { role: 'agent', text: 'Great news. Your blood pressure readings look stable. Keep up the good work with your medication routine.' },
      { role: 'patient', text: 'Thank you so much for checking in. Goodbye.' },
    ],
  },
  {
    id: 'C003',
    patient_name: 'Patricia Williams',
    phone: '(555) 345-6789',
    medication: 'Albuterol Inhaler',
    dosage: 'As needed, max 4x daily',
    duration: '5m 47s',
    cost: 2.45,
    outcome: 'escalated',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    needs_attention: true,
    ai_analysis: {
      quality_score: 65,
      sentiment: 'concerning',
      summary: 'Patient reports increased shortness of breath this week. Recommended to contact physician.',
      clinical_summary: 'Patient reports increased frequency of Albuterol inhaler use over the past 3 days, now using 3-4 times daily instead of usual 1-2 times. Reports new onset shortness of breath with minimal exertion. Chest tightness noted. Patient denies fever or cough. Recommends urgent physician contact for possible COPD exacerbation or asthma control medication adjustment.',
      recommended_action: 'urgent_escalation',
      response_completeness: 78,
      conversation_flow: 68,
      data_accuracy: 85,
      guardrail_compliance: 90,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'struggling with breathing',
      'What is your current weight in pounds?': '155',
      'What is your height in feet and inches?': '5 feet 4 inches',
      'How much weight have you lost this past month in pounds?': '0',
      'Any side effects from your medication this month?': 'needs more relief',
      'Are you satisfied with your rate of weight loss?': 'concerned',
      'What is your goal weight in pounds?': '140',
      'Any requests about your dosage?': 'increased usage needed',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'shortness of breath increased',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'yes - breathing concerns',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Hello Patricia, this is a medication follow-up call. How are you breathing today?' },
      { role: 'patient', text: 'Honestly, not great. I\'ve been using my inhaler a lot more than usual.' },
      { role: 'agent', text: 'How often have you been using it this week?' },
      { role: 'patient', text: 'About 3 or 4 times a day. Normally it\'s just once or twice. I\'m getting short of breath even walking around.' },
      { role: 'agent', text: 'That\'s concerning. Are you experiencing any chest tightness?' },
      { role: 'patient', text: 'Yes, a little bit of tightness when the shortness of breath starts.' },
      { role: 'agent', text: 'Patricia, I\'d like you to contact your doctor as soon as possible, or go to urgent care today. This could indicate your asthma needs better control. Can you do that?' },
      { role: 'patient', text: 'Yes, I can call my doctor right after this.' },
      { role: 'agent', text: 'Perfect. We\'re documenting this call and will also notify your healthcare team. Take care.' },
    ],
  },
  {
    id: 'C002',
    patient_name: 'Robert Chen',
    phone: '(555) 234-5678',
    medication: 'Metformin 500mg',
    dosage: '2 tablets twice daily',
    duration: '3m 15s',
    cost: 1.85,
    outcome: 'completed',
    timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    needs_attention: false,
    ai_analysis: {
      quality_score: 88,
      sentiment: 'positive',
      summary: 'Patient reports stable glucose levels. Compliance excellent.',
      clinical_summary: 'Patient demonstrates excellent medication adherence with Metformin 500mg twice daily. Recent fasting glucose levels averaging 118 mg/dL, within acceptable range. No hypoglycemic episodes reported. Patient follows recommended diet and exercise regimen. A1C checked 2 weeks ago at 6.8%. Continue current management plan.',
      recommended_action: 'routine_refill',
      response_completeness: 90,
      conversation_flow: 87,
      data_accuracy: 88,
      guardrail_compliance: 92,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'very well',
      'What is your current weight in pounds?': '182',
      'What is your height in feet and inches?': '5 feet 10 inches',
      'How much weight have you lost this past month in pounds?': '3',
      'Any side effects from your medication this month?': 'no',
      'Are you satisfied with your rate of weight loss?': 'yes',
      'What is your goal weight in pounds?': '170',
      'Any requests about your dosage?': 'no',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'no',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'no',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Hello Robert, calling about your Metformin prescription. How are your glucose levels?' },
      { role: 'patient', text: 'Pretty steady. I\'ve been checking them regularly.' },
      { role: 'agent', text: 'That\'s great to hear. Any side effects or concerns?' },
      { role: 'patient', text: 'No, everything is going smoothly. I\'m taking my pills as prescribed.' },
    ],
  },
  {
    id: 'C004',
    patient_name: 'James Martinez',
    phone: '(555) 456-7890',
    medication: 'Atorvastatin 20mg',
    dosage: '1 tablet daily',
    duration: '3m 58s',
    cost: 2.10,
    outcome: 'escalated',
    timestamp: new Date(Date.now() - 38 * 60000).toISOString(),
    needs_attention: true,
    ai_analysis: {
      quality_score: 62,
      sentiment: 'concerning',
      summary: 'Patient reports muscle pain and weakness. Possible statin-related myopathy.',
      clinical_summary: 'Patient reports new onset muscle pain and weakness in legs over past 2 weeks. Denies recent falls but concerned about mobility. Recent lipid panel showed LDL at 105 mg/dL. Recommends contacting physician for possible statin adjustment or myopathy evaluation.',
      recommended_action: 'urgent_escalation',
      response_completeness: 91,
      conversation_flow: 90,
      data_accuracy: 92,
      guardrail_compliance: 91,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'experiencing muscle pain',
      'What is your current weight in pounds?': '190',
      'What is your height in feet and inches?': '5 feet 11 inches',
      'How much weight have you lost this past month in pounds?': '1',
      'Any side effects from your medication this month?': 'muscle weakness and pain in legs',
      'Are you satisfied with your rate of weight loss?': 'no',
      'What is your goal weight in pounds?': '175',
      'Any requests about your dosage?': 'concerned about statin',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'muscle weakness',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'yes - muscle pain from medication',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Hi James, checking in on your Atorvastatin. Taking it as prescribed?' },
      { role: 'patient', text: 'Yes, every night before bed.' },
      { role: 'agent', text: 'Any muscle pain or weakness?' },
      { role: 'patient', text: 'No, feeling great.' },
    ],
  },
  {
    id: 'C005',
    patient_name: 'Linda Davis',
    phone: '(555) 567-8901',
    medication: 'Ibuprofen 400mg',
    dosage: 'Every 6-8 hours as needed',
    duration: '2m 22s',
    cost: 1.65,
    outcome: 'escalated',
    timestamp: new Date(Date.now() - 52 * 60000).toISOString(),
    needs_attention: true,
    ai_analysis: {
      quality_score: 58,
      sentiment: 'concerning',
      summary: 'Patient reports excessive Ibuprofen use and stomach pain. GI concerns.',
      clinical_summary: 'Patient reports increased Ibuprofen usage, now 4-5 doses daily instead of 1-2. New onset stomach pain and nausea reported. Concerned about GI bleeding risk with high-dose NSAID use. Recommends physician contact for alternative pain management and possible GI evaluation.',
      recommended_action: 'urgent_escalation',
      response_completeness: 85,
      conversation_flow: 84,
      data_accuracy: 86,
      guardrail_compliance: 88,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'stomach pain and nausea',
      'What is your current weight in pounds?': '165',
      'What is your height in feet and inches?': '5 feet 5 inches',
      'How much weight have you lost this past month in pounds?': '3',
      'Any side effects from your medication this month?': 'stomach pain, nausea',
      'Are you satisfied with your rate of weight loss?': 'no',
      'What is your goal weight in pounds?': '155',
      'Any requests about your dosage?': 'need different pain management',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'GI issues',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'yes - stomach concerns',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Linda, how\'s your arthritis and Ibuprofen working for you?' },
      { role: 'patient', text: 'Much better. Physical therapy is really helping too.' },
      { role: 'agent', text: 'That\'s wonderful. Any stomach problems with the medication?' },
      { role: 'patient', text: 'No, I\'m careful to take it with food.' },
    ],
  },
  {
    id: 'C006',
    patient_name: 'Michael Anderson',
    phone: '(555) 678-9012',
    medication: 'Amlodipine 5mg',
    dosage: '1 tablet daily',
    duration: '4m 11s',
    cost: 2.05,
    outcome: 'escalated',
    timestamp: new Date(Date.now() - 68 * 60000).toISOString(),
    needs_attention: true,
    ai_analysis: {
      quality_score: 64,
      sentiment: 'concerning',
      summary: 'Patient reports elevated blood pressure readings and severe headaches.',
      clinical_summary: 'Patient reports recent blood pressure spikes: 145/92, 148/95. New onset severe headaches and dizziness. Medication may need dose adjustment. Patient experiencing significant ankle swelling. Recommends urgent physician evaluation for hypertension management and possible dosage increase.',
      recommended_action: 'urgent_escalation',
      response_completeness: 89,
      conversation_flow: 88,
      data_accuracy: 90,
      guardrail_compliance: 91,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'having headaches',
      'What is your current weight in pounds?': '198',
      'What is your height in feet and inches?': '6 feet',
      'How much weight have you lost this past month in pounds?': '2',
      'Any side effects from your medication this month?': 'severe headaches, ankle swelling',
      'Are you satisfied with your rate of weight loss?': 'no',
      'What is your goal weight in pounds?': '180',
      'Any requests about your dosage?': 'needs adjustment',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'elevated blood pressure',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'yes - blood pressure concerns',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Michael, how are you doing with your blood pressure medication?' },
      { role: 'patient', text: 'Very well. My readings have been good.' },
      { role: 'agent', text: 'Any ankle swelling or headaches?' },
      { role: 'patient', text: 'None at all. I\'m really pleased with this medication.' },
    ],
  },
  {
    id: 'C007',
    patient_name: 'Barbara Taylor',
    phone: '(555) 789-0123',
    medication: 'Simvastatin 40mg',
    dosage: '1 tablet nightly',
    duration: '3m 34s',
    cost: 1.95,
    outcome: 'failed',
    timestamp: new Date(Date.now() - 85 * 60000).toISOString(),
    needs_attention: true,
    ai_analysis: {
      quality_score: 45,
      sentiment: 'neutral',
      summary: 'Patient line appeared to be busy. No connection established.',
      clinical_summary: 'Call failed - line appeared to be busy. Unable to verify medication compliance or any health concerns. Recommend retry within 24 hours.',
      recommended_action: 'follow_up_required',
      response_completeness: 10,
      conversation_flow: 0,
      data_accuracy: 0,
      guardrail_compliance: 100,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'no response',
      'What is your current weight in pounds?': 'no response',
      'What is your height in feet and inches?': 'no response',
      'How much weight have you lost this past month in pounds?': 'no response',
      'Any side effects from your medication this month?': 'no response',
      'Are you satisfied with your rate of weight loss?': 'no response',
      'What is your goal weight in pounds?': 'no response',
      'Any requests about your dosage?': 'no response',
      'Have you started any new medications or supplements since last month?': 'no response',
      'Do you have any new medical conditions since your last check-in?': 'no response',
      'Any new allergies?': 'no response',
      'Any surgeries since your last check-in?': 'no response',
      'Any questions for your doctor?': 'no response',
      'Has your shipping address changed?': 'no response',
    },
    transcript: [],
  },
  {
    id: 'C008',
    patient_name: 'David Thomas',
    phone: '(555) 890-1234',
    medication: 'Carbidopa/Levodopa',
    dosage: '1 tablet 3x daily',
    duration: '6m 19s',
    cost: 2.75,
    outcome: 'completed',
    timestamp: new Date(Date.now() - 105 * 60000).toISOString(),
    needs_attention: false,
    ai_analysis: {
      quality_score: 87,
      sentiment: 'positive',
      summary: 'Parkinson symptoms well-controlled. Medication timing appropriate.',
      clinical_summary: 'Patient taking Carbidopa/Levodopa 3x daily with proper spacing (6-8 hours apart). Parkinson\'s motor symptoms well-controlled with minimal tremor. No wearing-off effects noted. Patient reports stable mood. Medication timing working well before meals.',
      recommended_action: 'routine_refill',
      response_completeness: 87,
      conversation_flow: 87,
      data_accuracy: 88,
      guardrail_compliance: 89,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'good',
      'What is your current weight in pounds?': '172',
      'What is your height in feet and inches?': '5 feet 9 inches',
      'How much weight have you lost this past month in pounds?': '2',
      'Any side effects from your medication this month?': 'minimal',
      'Are you satisfied with your rate of weight loss?': 'yes',
      'What is your goal weight in pounds?': '165',
      'Any requests about your dosage?': 'no',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'no',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'no',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Hello David, checking in on your Parkinson\'s medication regimen.' },
      { role: 'patient', text: 'Doing well. Not much shaking today.' },
      { role: 'agent', text: 'Excellent. Taking your three daily doses as scheduled?' },
      { role: 'patient', text: 'Yes, morning, noon, and evening. Works well.' },
    ],
  },
  {
    id: 'C009',
    patient_name: 'Nancy Jackson',
    phone: '(555) 901-2345',
    medication: 'Levothyroxine 75mcg',
    dosage: '1 tablet daily, morning',
    duration: '2m 58s',
    cost: 1.75,
    outcome: 'completed',
    timestamp: new Date(Date.now() - 125 * 60000).toISOString(),
    needs_attention: false,
    ai_analysis: {
      quality_score: 90,
      sentiment: 'positive',
      summary: 'TSH levels stable. Patient very compliant with morning routine.',
      clinical_summary: 'Patient taking Levothyroxine 75mcg each morning on empty stomach, one hour before breakfast. Recent TSH level 2.1 (normal range 0.4-4.0). Patient reports good energy levels and no cold symptoms. Weight stable. Medication compliance excellent.',
      recommended_action: 'routine_refill',
      response_completeness: 90,
      conversation_flow: 91,
      data_accuracy: 89,
      guardrail_compliance: 93,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'very well',
      'What is your current weight in pounds?': '138',
      'What is your height in feet and inches?': '5 feet 3 inches',
      'How much weight have you lost this past month in pounds?': '1',
      'Any side effects from your medication this month?': 'no',
      'Are you satisfied with your rate of weight loss?': 'yes',
      'What is your goal weight in pounds?': '130',
      'Any requests about your dosage?': 'no',
      'Have you started any new medications or supplements since last month?': 'no',
      'Do you have any new medical conditions since your last check-in?': 'no',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'no',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Nancy, how\'s your thyroid medication working?' },
      { role: 'patient', text: 'Great! My energy is back to normal.' },
      { role: 'agent', text: 'Perfect. Still taking it every morning before breakfast?' },
      { role: 'patient', text: 'Absolutely, never miss it.' },
    ],
  },
  {
    id: 'C010',
    patient_name: 'Joseph White',
    phone: '(555) 012-3456',
    medication: 'Albuterol + Tiotropium',
    dosage: 'Albuterol as needed, Tiotropium 1x daily',
    duration: '5m 8s',
    cost: 2.35,
    outcome: 'escalated',
    timestamp: new Date(Date.now() - 145 * 60000).toISOString(),
    needs_attention: true,
    ai_analysis: {
      quality_score: 62,
      sentiment: 'concerning',
      summary: 'Patient reports recent hospitalization for COPD exacerbation. Recommended close follow-up.',
      clinical_summary: 'Patient discharged from hospital 5 days ago following COPD exacerbation. Currently on dual therapy (Albuterol rescue + Tiotropium maintenance). Reports mild residual cough and occasional dyspnea. Heart rate slightly elevated. Recommended: close monitoring for first 2 weeks post-discharge, pulmonologist follow-up scheduled.',
      recommended_action: 'follow_up_required',
      response_completeness: 85,
      conversation_flow: 72,
      data_accuracy: 88,
      guardrail_compliance: 92,
    },
    health_questionnaire: {
      'How have you been feeling overall?': 'improving daily',
      'What is your current weight in pounds?': '185',
      'What is your height in feet and inches?': '5 feet 9 inches',
      'How much weight have you lost this past month in pounds?': '3',
      'Any side effects from your medication this month?': 'mild cough',
      'Are you satisfied with your rate of weight loss?': 'yes',
      'What is your goal weight in pounds?': '170',
      'Any requests about your dosage?': 'no',
      'Have you started any new medications or supplements since last month?': 'prednisone taper',
      'Do you have any new medical conditions since your last check-in?': 'recently discharged',
      'Any new allergies?': 'no',
      'Any surgeries since your last check-in?': 'no',
      'Any questions for your doctor?': 'occasional dyspnea concerns',
      'Has your shipping address changed?': 'no',
    },
    transcript: [
      { role: 'agent', text: 'Hello Joseph, this is a post-hospitalization follow-up call. How are you feeling?' },
      { role: 'patient', text: 'I\'m doing better than I was. Still have a cough but not as bad as in the hospital.' },
      { role: 'agent', text: 'That\'s good to hear. You were just discharged 5 days ago. Are you taking both your Albuterol and Tiotropium?' },
      { role: 'patient', text: 'Yes, I\'m taking the daily one every morning and the rescue one when I need it, which is about 1-2 times a day now.' },
      { role: 'agent', text: 'Excellent. That\'s good improvement. How are you with your Prednisone taper?' },
      { role: 'patient', text: 'I\'m following the schedule. I\'m on day 4 of the taper.' },
      { role: 'agent', text: 'Perfect. We want to closely monitor you over the next two weeks. Do you have your pulmonology appointment?' },
      { role: 'patient', text: 'Yes, I have it next week.' },
      { role: 'agent', text: 'Great. If you experience increased shortness of breath or chest pain before then, go to the ER immediately. Otherwise, we\'ll check in with you in a few days.' },
    ],
  },
];

export const MOCK_STATS = {
  total_calls: 47,
  avg_duration: '4m 12s',
  total_cost: 98.35,
  completed_calls: 38,
  escalated_calls: 4,
  failed_calls: 5,
  average_quality_score: 84.2,
};
